apiVersion: v1
kind: Service
metadata:
  name: evolve-devops-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: evolve-devops-app
